[Clippy] Code maintenance
hove-io/loki pull request #223
Opened 2022-05-06 17:06 UTC by pbench

🤖 This is an automatic PR 🤖

Clippy suggests the following changes

2022-05-10 16:11 UTC, woshilapin requested changes

2022-05-10 16:11 UTC, woshilapin commented on random/src/main.rs
> +    launch::logger::init_logger();
I think this is not what we want, is it?

2022-05-11 09:49 UTC, pbench commented on random/src/main.rs
> +    launch::logger::init_logger();
This is ok here.
At some point, `launch::logger::init_logger()` was returning a guard that must live for the duration of the program.
It was changed, and now this function does not return anything.

2022-05-11 09:57 UTC, woshilapin approved these changes

2022-05-11 09:57 UTC, merged